version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/matchai
      - REDIS_HOST=redis
    depends_on:
      - mongo
      - redis
      - ai-service

  web:
    build: ./web
    ports:
      - "3002:80"
    depends_on:
      - backend

  mobile:
    build: ./mobile
    ports:
      - "19000:19000"
      - "19001:19001"
    depends_on:
      - backend

  admin:
    build: ./admin
    ports:
      - "3001:80"
    depends_on:
      - backend

  ai-service:
    build: ./ai-service
    ports:
      - "8000:8000"
    depends_on:
      - redis

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - admin

volumes:
  mongo_data: